#spring:
#  datasource:
#    password: password
#    username: sa
#    url: jdbc:h2:mem:hwmybatis
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  jpa:
#    defer-datasource-initialization: true
